<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jns_pembayaran extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->database();
        $this->load->model('Jns_pembayaran_model');
    } 

    /*
     * Listing of jns_pembayaran
     */
    function index()
    {
        // $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('jns_pembayaran/index?');
        $config['total_rows'] = $this->Jns_pembayaran_model->get_all_jns_pembayaran_count();
        // $this->pagination->initialize($config);

        $data['jns_pembayaran'] = $this->Jns_pembayaran_model->get_all_jns_pembayaran($params);
        
        $data['_view'] = 'jns_pembayaran/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new jns_pembayaran
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $this->load->library('form_validation');
            $this->form_validation->set_rules('id', 'ID Jenis Pembayaran', 'required');
            $this->form_validation->set_rules('jns_pembayaran', 'Jenis Pembayaran', 'required');
            if ($this->form_validation->run() == FALSE)
            $params = array(
				'jns_pembayaran' => $this->input->post('jns_pembayaran'),
            );
            
            $jns_pembayaran_id = $this->Jns_pembayaran_model->add_jns_pembayaran($params);
            redirect('jns_pembayaran/index');
        }
        else
        {            
            $data['_view'] = 'jns_pembayaran/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a jns_pembayaran
     */
    function edit($id)
    {   
        // check if the jns_pembayaran exists before trying to edit it
        $data['jns_pembayaran'] = $this->Jns_pembayaran_model->get_jns_pembayaran($id);
        
        if(isset($data['jns_pembayaran']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'jns_pembayaran' => $this->input->post('jns_pembayaran'),
                );

                $this->Jns_pembayaran_model->update_jns_pembayaran($id,$params);            
                redirect('jns_pembayaran/index');
            }
            else
            {
                $data['_view'] = 'jns_pembayaran/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The jns_pembayaran you are trying to edit does not exist.');
    } 

    /*
     * Deleting jns_pembayaran
     */
    function remove($id)
    {
        $jns_pembayaran = $this->Jns_pembayaran_model->get_jns_pembayaran($id);

        // check if the jns_pembayaran exists before trying to delete it
        if(isset($jns_pembayaran['id']))
        {
            $this->Jns_pembayaran_model->delete_jns_pembayaran($id);
            redirect('jns_pembayaran/index');
        }
        else
            show_error('The jns_pembayaran you are trying to delete does not exist.');
    }

    public function export(){
        // Skrip berikut ini adalah skrip yang bertugas untuk meng-export data tadi ke excel
        header("Content-type: application/vnd-ms-excel");
        header("Content-Disposition: attachment; filename=Data_Jns_pembayaran.xls");
        
        $data['jns_pembayaran'] = $this->Jns_pembayaran_model->get_all_jns_pembayaran();
        $this->load->view('jns_pembayaran/export', $data);
      }
    
}
