<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kamar extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kamar_model');
    } 

    /*
     * Listing of kamar
     */
    function index()
    {
        $data['kamar'] = $this->Kamar_model->get_all_kamar();
        
        $data['_view'] = 'kamar/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new kamar
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'jns_kamar' => $this->input->post('jns_kamar'),
				'harga_kamar' => $this->input->post('harga_kamar'),
            );
            
            $kamar_id = $this->Kamar_model->add_kamar($params);
            redirect('kamar/index');
        }
        else
        {            
            $data['_view'] = 'kamar/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a kamar
     */
    function edit($id)
    {   
        // check if the kamar exists before trying to edit it
        $data['kamar'] = $this->Kamar_model->get_kamar($id);
        
        if(isset($data['kamar']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'jns_kamar' => $this->input->post('jns_kamar'),
					'harga_kamar' => $this->input->post('harga_kamar'),
                );

                $this->Kamar_model->update_kamar($id,$params);            
                redirect('kamar/index');
            }
            else
            {
                $data['_view'] = 'kamar/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kamar you are trying to edit does not exist.');
    } 

    /*
     * Deleting kamar
     */
    function remove($id)
    {
        $kamar = $this->Kamar_model->get_kamar($id);

        // check if the kamar exists before trying to delete it
        if(isset($kamar['id']))
        {
            $this->Kamar_model->delete_kamar($id);
            redirect('kamar/index');
        }
        else
            show_error('The kamar you are trying to delete does not exist.');
    }
    
}
