<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pasien extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->database();
        $this->load->model('Pasien_model');
    } 

    /*
     * Listing of pasien
     */
    function index()
    {
        
        
        $data['_view'] = 'pasien/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pasien
     */
    function add()
    {   
        $this->load->library('form_validation');
        $this->form_validation->set_rules('id', 'ID Pasien', 'required');
        $this->form_validation->set_rules('nama_pasien', 'Nama Pasien', 'required');
        $this->form_validation->set_rules('tgl_masuk', 'Tanggal Masuk', 'required');
        $this->form_validation->set_rules('tgl_keluar', 'Tanggal Keluar', 'required');
        $this->form_validation->set_rules('jns_kamar', 'Jenis Kamar', 'required');
        $this->form_validation->set_rules('jns_penyakit', 'Jenis Penyakit', 'required');
        $this->form_validation->set_rules('alamat', 'Alamat', 'required');
        $this->form_validation->set_rules('no_tlp', 'No Telpon', 'required');
        $this->form_validation->run() == FALSE;
        if(isset($_POST) && count($_POST) > 0)
        {   
            $params = array(
				'jns_kelamin' => $this->input->post('jns_kelamin'),
				'jns_kamar' => $this->input->post('jns_kamar'),
				'jns_penyakit' => $this->input->post('jns_penyakit'),
				'nama_pasien' => $this->input->post('nama_pasien'),
				'tgl_masuk' => $this->input->post('tgl_masuk'),
				'tgl_keluar' => $this->input->post('tgl_keluar'),
				'alamat' => $this->input->post('alamat'),
				'no_tlp' => $this->input->post('no_tlp'),
            );
            
            $pasien_id = $this->Pasien_model->add_pasien($params);
            redirect('pasien/index');
        }
        else
        {
			$this->load->model('Kamar_model');
			$data['all_kamar'] = $this->Kamar_model->get_all_kamar();

			$this->load->model('Penyakit_model');
			$data['all_penyakit'] = $this->Penyakit_model->get_all_penyakit();
            
            $data['_view'] = 'pasien/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pasien
     */
    function edit($id)
    {   
        // check if the pasien exists before trying to edit it
        $data['pasien'] = $this->Pasien_model->get_pasien($id);
        
        if(isset($data['pasien']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'jns_kelamin' => $this->input->post('jns_kelamin'),
					'jns_kamar' => $this->input->post('jns_kamar'),
					'jns_penyakit' => $this->input->post('jns_penyakit'),
					'nama_pasien' => $this->input->post('nama_pasien'),
					'tgl_masuk' => $this->input->post('tgl_masuk'),
					'tgl_keluar' => $this->input->post('tgl_keluar'),
					'alamat' => $this->input->post('alamat'),
					'no_tlp' => $this->input->post('no_tlp'),
                );

                $this->Pasien_model->update_pasien($id,$params);            
                redirect('pasien/index');
            }
            else
            {
				$this->load->model('Kamar_model');
				$data['all_kamar'] = $this->Kamar_model->get_all_kamar();

				$this->load->model('Penyakit_model');
				$data['all_penyakit'] = $this->Penyakit_model->get_all_penyakit();

                $data['_view'] = 'pasien/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pasien you are trying to edit does not exist.');
    } 

    /*
     * Deleting pasien
     */
    function remove($id)
    {
        $pasien = $this->Pasien_model->get_pasien($id);

        // check if the pasien exists before trying to delete it
        if(isset($pasien['id']))
        {
            $this->Pasien_model->delete_pasien($id);
            redirect('pasien/index');
        }
        else
            show_error('The pasien you are trying to delete does not exist.');
    }

    public function export(){
        // Skrip berikut ini adalah skrip yang bertugas untuk meng-export data tadi ke excel
        header("Content-type: application/vnd-ms-excel");
        header("Content-Disposition: attachment; filename=Data_Pasien.xls");
        
        $data['pasien'] = $this->Pasien_model->get_all_pasien();
        $this->load->view('pasien/export', $data);
      }

      public function cetak(){
        ob_start();
        $data['pasien'] = $this->Pasien_model->get_all_pasien();
        $this->load->view('pasien/print', $data);
        $html = ob_get_contents();
            ob_end_clean();
            
            require_once('./assets/html2pdf/html2pdf.class.php');
        $pdf = new HTML2PDF('P','A3','en');
        $pdf->WriteHTML($html);
        $pdf->Output('Data_Pasien.pdf', 'D');
      }

      function get_data_pasien()
	{
		$list = $this->Pasien_model->join_table();
		$data = array();
		$no = $_POST['start'];
		foreach ($list as $field) {
			$row = array();
			$row[] = $field->id;
			$row[] = $field->nama_pasien;
			$row[] = $field->jns_kelamin;
            $row[] = $field->tgl_masuk;
            $row[] = $field->tgl_keluar;
            $row[] = $field->kamar;
            $row[] = $field->penyakit;
            $row[] = $field->alamat;
            $row[] = $field->no_tlp;
            $row[] ='<a href="edit/'.$field->id.'" class="btn btn-info btn-xs"><i class="fas fa-cog"> Edit</i></a>';
            $row[] ='<a href="remove/'.$field->id.'" onclick="del()" class="btn btn-danger btn-xs ml-3"><i class="fas fa-trash-alt"> Delete</i></a>';

			$data[] = $row;
		}

		$output = array(
			"draw" => $_POST['draw'],
			"recordsTotal" => $this->Pasien_model->count_all(),
			"recordsFiltered" => $this->Pasien_model->count_filtered(),
			"data" => $data,
		);
		//output dalam format JSON
		echo json_encode($output);
	}
    
}
