<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pembayaran extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pembayaran_model');
    } 

    /*
     * Listing of pembayaran
     */
    function index()
    {
        $data['pembayaran'] = $this->Pembayaran_model->get_all_pembayaran();
        
        $data['_view'] = 'pembayaran/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pembayaran
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('no_faktur','No Faktur','required|integer');
		$this->form_validation->set_rules('nama_pasien','Nama Pasien','required');
		$this->form_validation->set_rules('jns_kelamin','Jns Kelamin','required');
		$this->form_validation->set_rules('tgl_masuk','Tgl Masuk','required');
		$this->form_validation->set_rules('tgl_keluar','Tgl Keluar','required');
		$this->form_validation->set_rules('jns_kamar','Jns Kamar','required');
		$this->form_validation->set_rules('hrg_kamar','Hrg Kamar','required');
		$this->form_validation->set_rules('jns_penyakit','Jns Penyakit','required');
		$this->form_validation->set_rules('tindakan','Tindakan','required');
		$this->form_validation->set_rules('hrg_tindakan','Hrg Tindakan','required');
		$this->form_validation->set_rules('nama_obat','Nama Obat','required');
		$this->form_validation->set_rules('hrg_obat','Hrg Obat','required');
		$this->form_validation->set_rules('total_harga','Total Harga','required|integer');
		$this->form_validation->set_rules('nama_pembayar','Nama Pembayar','required');
		$this->form_validation->set_rules('jumlah_bayar','Jumlah Bayar','required|integer');
		$this->form_validation->set_rules('jns_pembayaran','Jns Pembayaran','required');
		$this->form_validation->set_rules('jns_card','Jns Card','required');
		$this->form_validation->set_rules('tgl_bayar','Tgl Bayar','required');
		$this->form_validation->set_rules('no_bukti','No Bukti','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_pasien' => $this->input->post('nama_pasien'),
				'jns_kamar' => $this->input->post('jns_kamar'),
				'hrg_kamar' => $this->input->post('hrg_kamar'),
				'jns_penyakit' => $this->input->post('jns_penyakit'),
				'tindakan' => $this->input->post('tindakan'),
				'hrg_tindakan' => $this->input->post('hrg_tindakan'),
				'nama_obat' => $this->input->post('nama_obat'),
				'hrg_obat' => $this->input->post('hrg_obat'),
				'jns_pembayaran' => $this->input->post('jns_pembayaran'),
				'jns_card' => $this->input->post('jns_card'),
				'no_faktur' => $this->input->post('no_faktur'),
				'jns_kelamin' => $this->input->post('jns_kelamin'),
				'tgl_masuk' => $this->input->post('tgl_masuk'),
				'tgl_keluar' => $this->input->post('tgl_keluar'),
				'total_harga' => $this->input->post('total_harga'),
				'nama_pembayar' => $this->input->post('nama_pembayar'),
				'jumlah_bayar' => $this->input->post('jumlah_bayar'),
				'tgl_bayar' => $this->input->post('tgl_bayar'),
				'no_bukti' => $this->input->post('no_bukti'),
            );
            
            $this->Pembayaran_model->transaction($params);
            redirect('pembayaran/index');
        }
        else
        {
			$this->load->model('Pasien_model');
			$data['all_pasien'] = $this->Pasien_model->get_all_pasien();

			$this->load->model('Kamar_model');
			$data['all_kamar'] = $this->Kamar_model->get_all_kamar();
			$data['all_kamar'] = $this->Kamar_model->get_all_kamar();

			$this->load->model('Penyakit_model');
			$data['all_penyakit'] = $this->Penyakit_model->get_all_penyakit();
			$data['all_penyakit'] = $this->Penyakit_model->get_all_penyakit();
			$data['all_penyakit'] = $this->Penyakit_model->get_all_penyakit();

			$this->load->model('Obat_model');
			$data['all_obat'] = $this->Obat_model->get_all_obat();
			$data['all_obat'] = $this->Obat_model->get_all_obat();

			$this->load->model('Jns_pembayaran_model');
			$data['all_jns_pembayaran'] = $this->Jns_pembayaran_model->get_all_jns_pembayaran();

			$this->load->model('Card_model');
			$data['all_card'] = $this->Card_model->get_all_card();
            
            $data['_view'] = 'pembayaran/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pembayaran
     */
    function edit($id)
    {   
        // check if the pembayaran exists before trying to edit it
        $data['pembayaran'] = $this->Pembayaran_model->get_pembayaran($id);
        
        if(isset($data['pembayaran']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('no_faktur','No Faktur','required|integer');
			$this->form_validation->set_rules('nama_pasien','Nama Pasien','required');
			$this->form_validation->set_rules('jns_kelamin','Jns Kelamin','required');
			$this->form_validation->set_rules('tgl_masuk','Tgl Masuk','required');
			$this->form_validation->set_rules('tgl_keluar','Tgl Keluar','required');
			$this->form_validation->set_rules('jns_kamar','Jns Kamar','required');
			$this->form_validation->set_rules('hrg_kamar','Hrg Kamar','required');
			$this->form_validation->set_rules('jns_penyakit','Jns Penyakit','required');
			$this->form_validation->set_rules('tindakan','Tindakan','required');
			$this->form_validation->set_rules('hrg_tindakan','Hrg Tindakan','required');
			$this->form_validation->set_rules('nama_obat','Nama Obat','required');
			$this->form_validation->set_rules('hrg_obat','Hrg Obat','required');
			$this->form_validation->set_rules('total_harga','Total Harga','required|integer');
			$this->form_validation->set_rules('nama_pembayar','Nama Pembayar','required');
			$this->form_validation->set_rules('jumlah_bayar','Jumlah Bayar','required|integer');
			$this->form_validation->set_rules('jns_pembayaran','Jns Pembayaran','required');
			$this->form_validation->set_rules('jns_card','Jns Card','required');
			$this->form_validation->set_rules('tgl_bayar','Tgl Bayar','required');
			$this->form_validation->set_rules('no_bukti','No Bukti','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_pasien' => $this->input->post('nama_pasien'),
					'jns_kamar' => $this->input->post('jns_kamar'),
					'hrg_kamar' => $this->input->post('hrg_kamar'),
					'jns_penyakit' => $this->input->post('jns_penyakit'),
					'tindakan' => $this->input->post('tindakan'),
					'hrg_tindakan' => $this->input->post('hrg_tindakan'),
					'nama_obat' => $this->input->post('nama_obat'),
					'hrg_obat' => $this->input->post('hrg_obat'),
					'jns_pembayaran' => $this->input->post('jns_pembayaran'),
					'jns_card' => $this->input->post('jns_card'),
					'no_faktur' => $this->input->post('no_faktur'),
					'jns_kelamin' => $this->input->post('jns_kelamin'),
					'tgl_masuk' => $this->input->post('tgl_masuk'),
					'tgl_keluar' => $this->input->post('tgl_keluar'),
					'total_harga' => $this->input->post('total_harga'),
					'nama_pembayar' => $this->input->post('nama_pembayar'),
					'jumlah_bayar' => $this->input->post('jumlah_bayar'),
					'tgl_bayar' => $this->input->post('tgl_bayar'),
					'no_bukti' => $this->input->post('no_bukti'),
                );

                $this->Pembayaran_model->transactionUpdate($id,$params);            
                redirect('pembayaran/index');
            }
            else
            {
				$this->load->model('Pasien_model');
				$data['all_pasien'] = $this->Pasien_model->get_all_pasien();

				$this->load->model('Kamar_model');
				$data['all_kamar'] = $this->Kamar_model->get_all_kamar();
				$data['all_kamar'] = $this->Kamar_model->get_all_kamar();

				$this->load->model('Penyakit_model');
				$data['all_penyakit'] = $this->Penyakit_model->get_all_penyakit();
				$data['all_penyakit'] = $this->Penyakit_model->get_all_penyakit();
				$data['all_penyakit'] = $this->Penyakit_model->get_all_penyakit();

				$this->load->model('Obat_model');
				$data['all_obat'] = $this->Obat_model->get_all_obat();
				$data['all_obat'] = $this->Obat_model->get_all_obat();

				$this->load->model('Jns_pembayaran_model');
				$data['all_jns_pembayaran'] = $this->Jns_pembayaran_model->get_all_jns_pembayaran();

				$this->load->model('Card_model');
				$data['all_card'] = $this->Card_model->get_all_card();

                $data['_view'] = 'pembayaran/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pembayaran you are trying to edit does not exist.');
    } 

    /*
     * Deleting pembayaran
     */
    function remove($id)
    {
        $pembayaran = $this->Pembayaran_model->get_pembayaran($id);

        // check if the pembayaran exists before trying to delete it
        if(isset($pembayaran['id']))
        {
            $this->Pembayaran_model->transactionDelete($id);
            redirect('pembayaran/index');
        }
        else
            show_error('The pembayaran you are trying to delete does not exist.');
    }
    
}

