<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pembayaran extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pembayaran_model');
    } 

    /*
     * Listing of pembayaran
     */
    function index()
    {
        $data['pembayaran'] = $this->Pembayaran_model->get_all_pembayaran();
        
        $data['_view'] = 'pembayaran/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pembayaran
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama_pasien' => $this->input->post('nama_pasien'),
				'jns_kelamin' => $this->input->post('jns_kelamin'),
				'jns_kamar' => $this->input->post('jns_kamar'),
				'hrg_kamar' => $this->input->post('hrg_kamar'),
				'jns_penyakit' => $this->input->post('jns_penyakit'),
				'tindakan' => $this->input->post('tindakan'),
				'hrg_tindakan' => $this->input->post('hrg_tindakan'),
				'nama_obat' => $this->input->post('nama_obat'),
				'hrg_obat' => $this->input->post('hrg_obat'),
				'jns_pembayaran' => $this->input->post('jns_pembayaran'),
				'jns_card' => $this->input->post('jns_card'),
				'tgl_masuk' => $this->input->post('tgl_masuk'),
				'tgl_keluar' => $this->input->post('tgl_keluar'),
				'total_harga' => $this->input->post('total_harga'),
				'kembalian' => $this->input->post('kembalian'),
				'kekurangan' => $this->input->post('kekurangan'),
            );
            
            $pembayaran_id = $this->Pembayaran_model->add_pembayaran($params);
            redirect('pembayaran/index');
        }
        else
        {
			$this->load->model('Pasien_model');
			$data['all_pasien'] = $this->Pasien_model->get_all_pasien();
			$data['all_pasien'] = $this->Pasien_model->get_all_pasien();

			$this->load->model('Kamar_model');
			$data['all_kamar'] = $this->Kamar_model->get_all_kamar();
			$data['all_kamar'] = $this->Kamar_model->get_all_kamar();

			$this->load->model('Penyakit_model');
			$data['all_penyakit'] = $this->Penyakit_model->get_all_penyakit();
			$data['all_penyakit'] = $this->Penyakit_model->get_all_penyakit();
			$data['all_penyakit'] = $this->Penyakit_model->get_all_penyakit();

			$this->load->model('Obat_model');
			$data['all_obat'] = $this->Obat_model->get_all_obat();
			$data['all_obat'] = $this->Obat_model->get_all_obat();

			$this->load->model('Jns_pembayaran_model');
			$data['all_jns_pembayaran'] = $this->Jns_pembayaran_model->get_all_jns_pembayaran();

			$this->load->model('Card_model');
			$data['all_card'] = $this->Card_model->get_all_card();
            
            $data['_view'] = 'pembayaran/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pembayaran
     */
    function edit($id)
    {   
        // check if the pembayaran exists before trying to edit it
        $data['pembayaran'] = $this->Pembayaran_model->get_pembayaran($id);
        
        if(isset($data['pembayaran']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama_pasien' => $this->input->post('nama_pasien'),
					'jns_kelamin' => $this->input->post('jns_kelamin'),
					'jns_kamar' => $this->input->post('jns_kamar'),
					'hrg_kamar' => $this->input->post('hrg_kamar'),
					'jns_penyakit' => $this->input->post('jns_penyakit'),
					'tindakan' => $this->input->post('tindakan'),
					'hrg_tindakan' => $this->input->post('hrg_tindakan'),
					'nama_obat' => $this->input->post('nama_obat'),
					'hrg_obat' => $this->input->post('hrg_obat'),
					'jns_pembayaran' => $this->input->post('jns_pembayaran'),
					'jns_card' => $this->input->post('jns_card'),
					'tgl_masuk' => $this->input->post('tgl_masuk'),
					'tgl_keluar' => $this->input->post('tgl_keluar'),
					'total_harga' => $this->input->post('total_harga'),
					'kembalian' => $this->input->post('kembalian'),
					'kekurangan' => $this->input->post('kekurangan'),
                );

                $this->Pembayaran_model->update_pembayaran($id,$params);            
                redirect('pembayaran/index');
            }
            else
            {
				$this->load->model('Pasien_model');
				$data['all_pasien'] = $this->Pasien_model->get_all_pasien();
				$data['all_pasien'] = $this->Pasien_model->get_all_pasien();

				$this->load->model('Kamar_model');
				$data['all_kamar'] = $this->Kamar_model->get_all_kamar();
				$data['all_kamar'] = $this->Kamar_model->get_all_kamar();

				$this->load->model('Penyakit_model');
				$data['all_penyakit'] = $this->Penyakit_model->get_all_penyakit();
				$data['all_penyakit'] = $this->Penyakit_model->get_all_penyakit();
				$data['all_penyakit'] = $this->Penyakit_model->get_all_penyakit();

				$this->load->model('Obat_model');
				$data['all_obat'] = $this->Obat_model->get_all_obat();
				$data['all_obat'] = $this->Obat_model->get_all_obat();

				$this->load->model('Jns_pembayaran_model');
				$data['all_jns_pembayaran'] = $this->Jns_pembayaran_model->get_all_jns_pembayaran();

				$this->load->model('Card_model');
				$data['all_card'] = $this->Card_model->get_all_card();

                $data['_view'] = 'pembayaran/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pembayaran you are trying to edit does not exist.');
    } 

    /*
     * Deleting pembayaran
     */
    function remove($id)
    {
        $pembayaran = $this->Pembayaran_model->get_pembayaran($id);

        // check if the pembayaran exists before trying to delete it
        if(isset($pembayaran['id']))
        {
            $this->Pembayaran_model->delete_pembayaran($id);
            redirect('pembayaran/index');
        }
        else
            show_error('The pembayaran you are trying to delete does not exist.');
    }
    
}
