<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Card_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get card by id
     */
    function get_card($id)
    {
        return $this->db->get_where('card',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all card count
     */
    function get_all_card_count()
    {
        $this->db->from('card');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all card
     */
    function get_all_card($params = array())
    {
        $this->db->order_by('jns_card', 'asc');
        if(isset($params) && !empty($params))
        {
            // $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('card')->result_array();
    }
        
    /*
     * function to add new card
     */
    function add_card($params)
    {
        $this->db->insert('card',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update card
     */
    function update_card($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('card',$params);
    }
    
    /*
     * function to delete card
     */
    function delete_card($id)
    {
        return $this->db->delete('card',array('id'=>$id));
    }
}
