<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jns_pembayaran_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get jns_pembayaran by id
     */
    function get_jns_pembayaran($id)
    {
        return $this->db->get_where('jns_pembayaran',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all jns_pembayaran count
     */
    function get_all_jns_pembayaran_count()
    {
        $this->db->from('jns_pembayaran');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all jns_pembayaran
     */
    function get_all_jns_pembayaran($params = array())
    {
        $this->db->order_by('jns_pembayaran', 'asc');
        if(isset($params) && !empty($params))
        {
            // $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('jns_pembayaran')->result_array();
    }
        
    /*
     * function to add new jns_pembayaran
     */
    function add_jns_pembayaran($params)
    {
        $this->db->insert('jns_pembayaran',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update jns_pembayaran
     */
    function update_jns_pembayaran($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('jns_pembayaran',$params);
    }
    
    /*
     * function to delete jns_pembayaran
     */
    function delete_jns_pembayaran($id)
    {
        return $this->db->delete('jns_pembayaran',array('id'=>$id));
    }
}
