<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kamar_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kamar by id
     */
    function get_kamar($id)
    {
        return $this->db->get_where('kamar',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all kamar
     */
    function get_all_kamar()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('kamar')->result_array();
    }
        
    /*
     * function to add new kamar
     */
    function add_kamar($params)
    {
        $this->db->insert('kamar',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kamar
     */
    function update_kamar($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('kamar',$params);
    }
    
    /*
     * function to delete kamar
     */
    function delete_kamar($id)
    {
        return $this->db->delete('kamar',array('id'=>$id));
    }
}
